backend:
  name: git-gateway
  branch: master 

media_folder: "public/images" 
public_folder: "/images"

collections:
  - name: "pages" 
    label: "Pages" 
    folder: "pages" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
